#!/usr/bin/env php
<?php

foreach ([
  __DIR__ . '/dist/private/vendor/autoload.php',
  __DIR__ .      '/private/vendor/autoload.php',
  __DIR__ .              '/vendor/autoload.php',
] as $file) {
  if (file_exists($file)) {
    define('COMPOSER_INSTALL', $file);
    break;
  }
}

require(COMPOSER_INSTALL);

$output = SchornIO\StaticWebsiteGenerator\TemplateCompiler::compile();

echo($output);

?>
