#!/usr/bin/env php
<?php

foreach ([
  __DIR__ .          '/autoload.php',
  __DIR__ .       '/../autoload.php',
  __DIR__ .    '/../../autoload.php',
  __DIR__ . '/../../../autoload.php',
  __DIR__ .   '/vendor/autoload.php',
] as $file) {
  if (file_exists($file)) {
    define('COMPOSER_INSTALL', $file);
    break;
  }
}

require(COMPOSER_INSTALL);

$optionParameter  = [
    "tokenVersion:",
    "token:",
];

$options = getopt("", $optionParameter);

$output = SchornIO\StaticWebsiteGenerator\GeneratorManager::runAllGenerators($options["tokenVersion"], $options["token"]);

echo($output);

?>
