#!/usr/bin/env php
<?php

foreach ([
  __DIR__ .          '/autoload.php',
  __DIR__ .       '/../autoload.php',
  __DIR__ .    '/../../autoload.php',
  __DIR__ . '/../../../autoload.php',
] as $file) {
  if (file_exists($file)) {
    define('COMPOSER_INSTALL', $file);
    break;
  }
}

require(COMPOSER_INSTALL);

$output = SchornIO\StaticWebsiteGenerator\TemplateCompiler::compile();

echo($output);

?>
