#!/usr/bin/env php
<?php

foreach ([
  __DIR__ .          '/autoload.php',
  __DIR__ .       '/../autoload.php',
  __DIR__ .    '/../../autoload.php',
  __DIR__ . '/../../../autoload.php',
  __DIR__ .   '/vendor/autoload.php',
] as $file) {
  if (file_exists($file)) {
    define('COMPOSER_INSTALL', $file);
    break;
  }
}

require(COMPOSER_INSTALL);

$templateIndex = file_get_contents("php://stdin");

$output = SchornIO\StaticWebsiteGenerator\TemplateCompiler::compile($templateIndex);

echo($output);

?>
